### PR TITLE
Activation of the NPU Accelerator.

### PR DESCRIPTION
**Pull request by maly-phy**

### CODE REVIEW

**Review by sriedmueller — CHANGES_REQUESTED** [review]
Hi @maly-phy,
your commit message does not make much sense. Please firmly describe what you did and why you did it in the commit message.

**Review by sriedmueller — CHANGES_REQUESTED** [review]
What are you doing here? Why did you add another file, which is not used anywhere by the way?
I only asked to reword the previous commit message.
Please keep the subject line of your commit message under 80 characters. It should look like this:
```
<Subject line under 80 characters>
<empty line>
<Commit message/description, can be multiple lines and paragraphs>
<empty line>
<Signed-off-by>
```
Also make sure to add your Signed-off-by to your commit messages.

**Review by sriedmueller — CHANGES_REQUESTED** [review]
Hi @maly-phy,
now you have three commits instead of one. In the end there should only be one commit.

In your subject line you reference the PD22.1.0 release but the demo itself does not really care about BSP versions. It could also be used independently from our BSPs. Thus try to avoid references to our BSPs. Your subject line could look like this:
"Enable the use of the NPU explicitly" and in the description you could mention that this is required for NXPs hardknott release to make use of the NPU.

Also please wrap your commit messages at 80 characters per line and your signed-off-by needs to contain your email address as well. Please have a look at `git commit -s` to automatically add the signed-off-by when committing. Also have a look at this:
https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Review by sriedmueller — CHANGES_REQUESTED** [review]
Hi @maly-phy,
plaese wrap the commit message at 80 characters per line.
With that change I think we're good to go.

**Comment by maly-phy** [comment]
> plaese wrap the commit message at 80 characters per line.
> With that change I think we're good to go.

You mentioned before that the commit message can be multiple lines or paragraphs. The subject line is only 33 characters.

**Comment by sriedmueller** [comment]
> > plaese wrap the commit message at 80 characters per line.
> > With that change I think we're good to go.
> 
> You mentioned before that the commit message can be multiple lines or paragraphs. The subject line is only 33 characters.

Yes multiple lines. Your commit message (not the subject line) has just one line. Please change it, that each line in your commit message only has a maximum of 80 characters. So please break your lines so they do not exceed 80 characters.
Here is what I mean:
```
Activation of the NPU accelerator

Enabled the NPU accelerator by adding the path to the external delegate library
inside the model initialisation function. This allows utilizing the hardware
accelerator driver (OpenVX) to use the accelerator capabilities. The NPU had to
be enabled inside the ai.py code since it is not the default settings in the
hardknott release of the NXP.

Signed-off-by: Mohamed Aly <m.aly@phytec.de>
```

**Review by sriedmueller — APPROVED** [review]

**Pull request merged**
